- hosts: smabap_vir_app_server
  vars:
  - upgsapkrn_input_sap_sid: "DSA"
  roles:
  - {role: upgrade_sap_kernel}
- hosts: smjava_vir_app_server
  vars:
  - upgsapkrn_input_sap_sid: "DSJ"
  roles:
  - {role: upgrade_sap_kernel}
 # - role: <ansible_dir>/roles/upgrade_sap_kernel