---
###########################################
# tasks file for sap_startInstance
###########################################
- name: Start SAP instances
  command: "{{ sapctr_exe_dir }}/sapcontrol -nr {{ item.split()[1]|replace(',', '') }} -function InstanceStart {{ item.split()[0]|replace(',', '') }} {{ item.split()[1]|replace(',', '') }}"
  environment:
    LIBPATH: "{{ sapctr_exe_dir }}"
  args:
    chdir: "{{ sapctr_exe_dir }}"
  with_items: "{{ running_sap_nr }}"
  register: result

- name: wait starting SAP instances {{ running_sap_nr }}
  command: "{{ sapctr_exe_dir }}/sapcontrol -nr {{ item }} -function WaitforStarted 1200 5"
  environment:
    LIBPATH: "{{ sapctr_exe_dir }}"
  args:
    chdir: "{{ sapctr_exe_dir }}"
  with_items: "{{ running_sap_nr }}"
  register: result

