---
# defaults for upgrade_sap_kernel

# set variable: sapadm
sap_adm: "{{ sap_sid|lower }}adm"

# set variable: sapsys
sap_sys: "sapsys"

# Directory path on the Ansible host where SAR file is located
sap_kernel_upgrade_download_local_path: "/tmp/sar_prov_dir"

# Directory path on the Ansible host where SAPCAR is located
sap_sapcar_download_local_path: "/tmp/sapcar_prov_dir"

# Directory path on the Ansible host where SAR file is located
sap_sapcar_local_path_default: "/usr/sap/hostctrl/exe"

# Temporary directory path that will be created on the target host
sap_kernel_upgrade_dest_dir: "/usr/sap/tmp/kernel_temp_dir"

# Local SAPCAR file name
sap_sapcar_file_name: "SAPCAR"

# Temporary dirctory path that will be created on the target host
sap_kernel_upgrade_tmp_dir: "/sapmnt/{{ sap_sid }}/exe/uc/kernel_interims_dir"

# Directory path of SAP working directory
sap_kernel_upgrade_dir: "/sapmnt/{{ sap_sid }}/exe/uc/kernel_working_dir"