---
# Temporary directory path, that will be created on the target host
sap_hostagent_agent_tmp_directory: "/tmp/hostctrl"

# Directory path on the Ansible host where SAR file is located
sap_hostagent_download_local_path: "/tmp/downloads"

# Directory path on the Ansible host where SAPCAR is located
sap_sapcar_download_local_path: "/tmp/sapcar"

# Directory on the target host where SAPCAR is searched by default
sap_sapcar_local_path_default: "/usr/sap/hostctrl/exe"

# Default SAPCAR file name
sap_hostagent_sapcar_file_name: "SAPCAR"

# Boolean variable to indicate if the temporary directory on the target host will be removed or not after the installation
sap_hostagent_clean_tmp_directory: True



