---
###########################################
# tasks file for sap_stopInstance
###########################################
- name: stop SAP instances {{ running_sap_nr }}
  command: "{{ sapctr_exe_dir }}/sapcontrol -nr {{ item.split()[1]|replace(',', '') }} -function InstanceStop {{ item.split()[0]|replace(',', '') }} {{ item.split()[1]|replace(',', '') }}{{ sap_softtimeout }}"
  environment:
    LIBPATH: "{{ sapctr_exe_dir }}"
  args:
    chdir: "{{ sapctr_exe_dir }}"
  with_items: "{{ running_sap_nr }}"
  register: result
  
- name: wait stopping SAP instances
  command: "{{ sapctr_exe_dir }}/sapcontrol -nr {{ item }} -function WaitforStopped 1200 5 "
  environment:
    LIBPATH: "{{ sapctr_exe_dir }}"
  args:
    chdir: "{{ sapctr_exe_dir }}"
  with_items: "{{ running_sap_nr }}"
  register: result
