---
###########################################
# tasks file for sap_kernel_upgrade
######################################################
# copy files to SAP kernel exe dir
######################################################
- name: Copy extracted files into kernel dir {{ upgsapkrn_dir_upgrade_kernel }}
  become_user: "{{ upgsapkrn_input_sap_adm }}"
  become: yes
  shell: "cp -rp {{ upgsapkrn_dir_extracted_sar_managednode }}/* {{ upgsapkrn_dir_upgrade_kernel }}"
  environment:
    LIBPATH: "{{ upgsapkrn_dir_upgrade_kernel }}"
  args:
    chdir: "{{ upgsapkrn_dir_upgrade_kernel }}"
  register: result_files
  failed_when: result_files.rc >= 2
######################################################
## Post Kernel Upg
#######################################################
- name: Execute saproot script
  become: yes
  shell: "{{ upgsapkrn_dir_upgrade_kernel }}/saproot.sh {{ upgsapkrn_input_sap_sid }}"
  environment:
    LIBPATH: "{{ upgsapkrn_dir_upgrade_kernel }}"
  args:
    chdir: "{{ upgsapkrn_dir_upgrade_kernel }}"